In [70]:
import re
import numpy as np
from scipy.spatial import distance
file = open('file_asd.txt', 'r+')
str_mass = []
for line in file:
        str_mass.append(line)
dictionary = {}
counter = 0
reshape_matrix = []
new_dict = []
for i in range(len(str_mass)):
    str_mass[i] = str_mass[i].lower()
    split_str = re.split('[^a-z]', str_mass[i])
    split_str = [x for x in split_str if x != '']
    reshape_matrix.append(split_str)
    for word in split_str:
        if word != '' and (word not in dictionary):
            new_dict.append(word)
            dictionary[word] = counter
matrix = np.zeros((22,254))
for i in range (22):
    for j in range (254):
        word_new = reshape_matrix[i]
        matrix[i,j] = word_new.count(new_dict[j])

In [71]:
matrix

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 1., 1.]])

In [73]:
print(distance.cosine(matrix[0],matrix[2]))

0.8644738145642124


In [92]:
dist_mart = []
for i in range (22):
    dist_mart.append(distance.cosine(matrix[0],matrix[i]))

In [101]:
dist_new = np.array(dist_mart)
dist_mart

[0.0,
 0.9527544408738466,
 0.8644738145642124,
 0.8951715163278082,
 0.7770887149698589,
 0.9402385695332803,
 0.7327387580875756,
 0.9258750683338899,
 0.8842724875284311,
 0.9055088817476932,
 0.8328165362273942,
 0.8804771390665607,
 0.8396432548525454,
 0.8703592552895671,
 0.8740118423302576,
 0.9442721787424647,
 0.8406361854220809,
 0.956644501523794,
 0.9442721787424647,
 0.8885443574849294,
 0.8427572744917122,
 0.8250364469440588]

In [96]:
dist_new

array([0.        , 0.95275444, 0.86447381, 0.89517152, 0.77708871,
       0.94023857, 0.73273876, 0.92587507, 0.88427249, 0.90550888,
       0.83281654, 0.88047714, 0.83964325, 0.87035926, 0.87401184,
       0.94427218, 0.84063619, 0.9566445 , 0.94427218, 0.88854436,
       0.84275727, 0.82503645])

In [98]:
result = np.argpartition(dist_new, 3)

In [99]:
result

array([ 4,  0,  6, 21,  3,  5,  2,  7,  8,  9,  1, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 10], dtype=int64)